on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew shadowJar

      - name: Rename file
        run: mv build/libs/KotlinTelegramBot-1.0-SNAPSHOT-all.jar bot.jar

      - name: Deploy and Restart Bot
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22222
          script: |
            rm -f /botSource/bot.jar
            rm -f /botSource/words.txt            
            
            scp -P 22222 -o StrictHostKeyChecking=no $HOME/bot.jar $SSH_USER@$SSH_HOST:/botSource/
            scp -P 22222 -o StrictHostKeyChecking=no $HOME/words.txt $SSH_USER@$SSH_HOST:/botSource/
            
            sudo systemctl restart english-learning-bot